-- programs: 서비스가 제공하는 공용 프로그램(공연) 카탈로그.
-- bookmark_items와 같은 성격(공용, 사용자가 직접 생성하지 않음)이지만
-- 실제 필요한 필드가 달라 별도 테이블로 분리 (기존 구조와 의미 충돌 방지).
create table public.programs (
  id bigint generated by default as identity primary key,
  title text not null,
  en_title text,
  date_label text not null,
  day text not null,
  start_time text not null,
  place text not null,
  genre text not null,
  tags text[],
  artist text not null,
  duration_label text not null,
  audience text not null,
  description text not null,
  image_url text,
  created_at timestamptz not null default now()
);

alter table public.programs enable row level security;

create policy "programs_select_all"
  on public.programs
  for select
  to anon, authenticated
  using (true);

-- user_schedules: 어떤 사용자가 어떤 프로그램을 자신의 "내 일정"에 담았는지.
-- user_bookmarks와 같은 성격(사용자별 관계 데이터)이지만 참조 대상이
-- bookmark_items가 아닌 programs이므로 별도 테이블로 분리.
create table public.user_schedules (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id),
  program_id bigint not null references public.programs (id),
  created_at timestamptz not null default now(),
  unique (user_id, program_id)
);

alter table public.user_schedules enable row level security;

create policy "user_schedules_select_own"
  on public.user_schedules
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "user_schedules_insert_own"
  on public.user_schedules
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "user_schedules_update_own"
  on public.user_schedules
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "user_schedules_delete_own"
  on public.user_schedules
  for delete
  to authenticated
  using (auth.uid() = user_id);
