-- 서비스에서 미리 제공하는 북마크 항목 (사용자가 직접 생성하지 않음)
create table public.bookmark_items (
  id bigint generated by default as identity primary key,
  url text not null,
  title text not null,
  description text,
  thumbnail_url text,
  created_at timestamptz not null default now()
);

alter table public.bookmark_items disable row level security;
