-- 사용자가 bookmark_items 중 하나를 자신의 북마크 목록에 추가했다는 관계
-- user_id는 Supabase Auth 사용자를 식별하는 값
create table public.user_bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  item_id bigint not null references public.bookmark_items (id),
  folder_id bigint references public.folders (id),
  created_at timestamptz not null default now(),
  unique (user_id, item_id)
);

alter table public.user_bookmarks disable row level security;
