-- 사용자가 자신의 북마크를 분류하기 위해 만드는 폴더
-- user_id는 Supabase Auth 사용자를 식별하는 값 (아직 FK 설정하지 않음)
create table public.folders (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  name text not null,
  created_at timestamptz not null default now()
);

alter table public.folders disable row level security;
